[project]
name = "activity-05-french-creek"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "gatorgrade",
    "pytest",
    "pytest-timeout",
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = [
    "tests"
]
timeout = 5
filterwarnings = [
    "ignore::pytest.PytestAssertRewriteWarning",
]
